---
- name: Download sanaei xui
  get_url:
    url: "{{ sanaei_xui_url }}"
    dest: /tmp/sanaei.sh
    mode: 755

- name: Install sanaei xui
  become: true
  expect:
    command: "/tmp/sanaei.sh"
    echo: true
    responses:
      - "y"
      - "{{ sanaei_xui_username }}"
      - "{{ sanaei_xui_password }}"
      - "{{ sanaei_xui_port }}"

- name: Setup warp plus
  become: true
  expect:
    command: "x-ui"
    echo: true
    responses:
      - "18" # WARP Management
      - "2" # Account Type (free, plus, team)
      - "2" # Change to another WARP+ account
      - "{{ warp_token }}"

- name: Install Fail2ban
  become: true
  expect:
    command: "x-ui"
    echo: true
    responses:
      - "17" # IP Limit Management
      - "1" # Install Fail2ban and configure IP Limit
      - "y"
      - ""
